### ISSUE TITLE
Windows batch processing

### ISSUE THREAD

**Issue by samhutchins** [JMoVS/installing_video_transcoding_on_windows#5]
We should add some information about batch processing in Windows. I'll put together a basic batch file, and I imagine it's possible to use a shell script in LXSS. I can have a crack at that too, unless you wanna do that @JMoVS?

**Comment by JMoVS** [comment]
I think it is possible, but neither do I have the time nor the experience currently to do that. So I very welcome you doing it!

**Comment by lisamelton** [comment]
@samhutchins This is a great idea! I would help but I don't think I've written a Windows batch file since I was at Adobe working on Illustrator in the early 90s. :)

**Comment by JMoVS** [comment]
closed with https://github.com/JMoVS/installing_video_transcoding_on_windows/commit/32a3b1388dcc8f0e462a68b7ece405c778c2d2b9 by @samhutchins !
